name: 'Maven Tests'
description: 'Runs maven build on the targeted EXCLUDE_PROJECT'
inputs:
  GH_USERNAME:
    required: true
  GH_TOKEN:
    required: true
  MAVEN_REPO:
    required: false
    default: '.m2/repository'
  MAVEN_CLI_OPTS:
    required: false
    default: '-s .m2/settings.xml'
  MAVEN_OPTS:
    required: false
    default: '-Dmaven.repo.local=.m2/repository'
  EXCLUDE_PROJECT:
    required: true

runs:
  using: composite
  steps:
    - name: Cache maven packages
      uses: actions/cache@v4
      with:
        path: ${{ inputs.MAVEN_REPO }}
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Install git
      shell: bash
      run: |
        sudo apt-get update -y
        sudo apt-get install -y git
        git config --global user.email "icarodamiani@gmail.com"
        git config --global user.name "icarodamiani"

    - name: Build
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.GH_TOKEN }}
        GH_USERNAME: ${{ inputs.GH_USERNAME }}
        GH_TOKEN: ${{ inputs.GH_TOKEN }}
      run: |
        ./mvnw ${{ inputs.MAVEN_CLI_OPTS }} clean install -pl !${{ inputs.EXCLUDE_PROJECT }} -U -P dev

    - name: "Deploy snapshot"
      shell: bash
      env:
        GH_USERNAME: ${{ inputs.GH_USERNAME }}
        GH_TOKEN: ${{ inputs.GH_TOKEN }}
      run: |
        ./mvnw ${{ inputs.MAVEN_CLI_OPTS }} deploy -pl !${{ inputs.EXCLUDE_PROJECT }}

    - name: Archive production artifacts
      uses: actions/upload-artifact@v4
      with:
        name: jar
        path: target/*.jar